### ISSUE TITLE
Fails to build on Arch Linux

### ISSUE THREAD

**Issue by gld1982ltd** [vera-desktop/vera#5]
I get this error during the build 

Unable to compile library vera:
 - Unable to find Vala package xscrnsaver

**Comment by g7** [comment]
Hello,

xscrnsaver is provided by libxss. In Debian you should install libxss-dev, I guess a similar package is available in Arch too.


Eugenio

**Comment by gld1982ltd** [comment]
Yes, I have libxss installed on my system.

**Comment by gld1982ltd** [comment]
I tried building with lib32-libxss  installed as well. No Go.

**Comment by g7** [comment]
Which version of bake are you using to build vera?


Eugenio

**Comment by gld1982ltd** [comment]
I am using bake 0.1.49

**Comment by g7** [comment]
You may try copying src/vapis/xscrnsaver.vapi to /usr/share/vala/vapi/ and re-try.

Eugenio

**Comment by gld1982ltd** [comment]
That is a good work around, but how can this build without having to manually copy the file? 

I am installing with this aur package https://aur4.archlinux.org/packages/vera-desktop-environment/

**Comment by g7** [comment]
Ideally, it should work out-of-the-box: the Recipe file specifies the internal ./vapis directory as a valid vapidir (https://github.com/vera-desktop/vera/blob/master/src/Recipe#L37). And I know it works because it builds fine in our build server (which is not tainted with development vapis, headers and so on).

We are using a slightly older version of bake though, 0.1.33. The behaviour of vala-compile-flags may have been changed in the version you are using.
I'll investigate more in this regard.


Eugenio

**Comment by gld1982ltd** [comment]
It seems that my system is not reading from the vapidir specified in the recipe. Any ideas?

**Comment by g7** [comment]
It may very well that your version of bake changed something. I'm in the process of upgrading bake in our development channel (see more at https://github.com/semplice/bake/commits/semplice).
Currently I'm blocked by some tests failing. I hope to resolve the issue and try recompiling vera with the latest version of bake.

Eugenio

**Comment by g7** [comment]
So I can confirm that the latest bake version doesn't make vera to compile.

This is caused by bake now checking the vapis before building (previously no check was done and valac would simply fail if no vapi is found), of course skipping our directory as --vapidir is used only during compilation and not before.

I'm now thinking on what to do to fix the issue. I can patch bake itself to support custom vapidirs but I don't want to divert too much from upstream (even if it is pretty much dead) or move the custom vapis to separate packages that install the vapis in the correct directories (as they are not vera-related). I think I'll go with the latter option but don't fully know yet :)

Eugenio

**Comment by g7** [comment]
As of ba8b54b, vera doesn't require the custom vapidir anymore.

The xscrnsaver bindings have been moved in a separate package, libxss-vapi. You can find it here: https://github.com/semplice/libxss-vapi


Eugenio

**Comment by enricocid** [comment]
solved by installing 

libxss-vapi-git from aur

https://aur.archlinux.org/packages/libxss-vapi-git/

**Comment by g7** [comment]
Yup, I guess that that PKGBUILD was created by gld1982ltd once I fixed this bug :)


Eugenio

**Comment by enricocid** [comment]
i had problems with this package

https://aur.archlinux.org/packages/vera-desktop-environment/

anyway, I have problems starting a vera session... it hangs :/

**Comment by g7** [comment]
Which plugins have you installed? Have you also installed alan2?

Eugenio

**Comment by enricocid** [comment]
I have installed vera-desktop-env and vera-x-settings packages but no plugins 
what are the minimum packages/plugins requirements?

Enrico

**Comment by g7** [comment]
It depends on what you need :) Semplice ships with the tint2 plugin (panel), openbox plugin (WM), desktop plugin (wallpaper + launcher), alan-watcher plugin (watcher for alan2), power plugin (power tray, you'll need also vera-power-manager) + alan2 (openbox menu builder) + vera-control-center (control center)


Eugenio
